all:
	cd detail/pop_mylib_ext && ./make_pop_headerguards.py
	cd detail/pop_mylib_ext && ./make_pop_macros.py
	cd detail/push_mylib_ext && ./make_push_headerguards.py
	cd detail/push_mylib_ext && ./make_push_macros.py
