#ifdef MYLIB_VENDORIZE_EXT

#ifdef EXT_DEFINE_MACRO_HPP
#define MYLIB_EXT_DEFINE_MACRO_HPP_HEADERGUARD
#endif // #ifdef EXT_DEFINE_MACRO_HPP
#pragma pop_macro("EXT_DEFINE_MACRO_HPP")

#ifdef EXT_PRINT_MACRO_HPP
#define MYLIB_EXT_PRINT_MACRO_HPP_HEADERGUARD
#endif // #ifdef EXT_PRINT_MACRO_HPP
#pragma pop_macro("EXT_PRINT_MACRO_HPP")

#ifdef EXT_RETURN_MACRO_HPP
#define MYLIB_EXT_RETURN_MACRO_HPP_HEADERGUARD
#endif // #ifdef EXT_RETURN_MACRO_HPP
#pragma pop_macro("EXT_RETURN_MACRO_HPP")

#endif // #ifdef MYLIB_VENDORIZE_EXT
