
#pragma push_macro("EXT_DEFINE_MACRO_HPP")
#ifndef MYLIB_EXT_DEFINE_MACRO_HPP_HEADERGUARD
#undef EXT_DEFINE_MACRO_HPP
#endif // #ifndef MYLIB_EXT_DEFINE_MACRO_HPP_HEADERGUARD

#pragma push_macro("EXT_PRINT_MACRO_HPP")
#ifndef MYLIB_EXT_PRINT_MACRO_HPP_HEADERGUARD
#undef EXT_PRINT_MACRO_HPP
#endif // #ifndef MYLIB_EXT_PRINT_MACRO_HPP_HEADERGUARD

#pragma push_macro("EXT_RETURN_MACRO_HPP")
#ifndef MYLIB_EXT_RETURN_MACRO_HPP_HEADERGUARD
#undef EXT_RETURN_MACRO_HPP
#endif // #ifndef MYLIB_EXT_RETURN_MACRO_HPP_HEADERGUARD
